name: Test Hello World

on:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set lowercase owner
        id: owner
        run: echo "value=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ steps.owner.outputs.value }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push hello
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ghcr.io/${{ steps.owner.outputs.value }}/hello:test
          file: .devops/Dockerfile.hello
